# Generated by Django 3.2a1 on 2021-07-02 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('ensayo', '0002_ensayo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ensayo',
            name='User',
        ),
        migrations.AddField(
            model_name='ensayo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
    ]
