# Generated by Django 3.2a1 on 2021-07-06 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ensayo', '0003_auto_20210701_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ensayo',
            name='user',
        ),
        migrations.AddField(
            model_name='ensayo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
