# Generated by Django 3.2a1 on 2021-09-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayo', '0004_auto_20210706_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensayo',
            name='mar_conclu',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='mar_premisa',
            field=models.CharField(default='0', max_length=1000),
        ),
    ]
