# Generated by Django 3.2a1 on 2021-09-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayo', '0007_auto_20210913_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensayo',
            name='numparrafos',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='ensayo',
            name='texto',
            field=models.CharField(max_length=2000),
        ),
    ]
