# Generated by Django 3.2a1 on 2021-10-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayo', '0008_auto_20210920_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensayo',
            name='promedia',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='ensayo',
            name='numparrafos',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='ensayo',
            name='texto',
            field=models.CharField(max_length=10000),
        ),
    ]
