# Generated by Django 3.2a1 on 2021-10-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayo', '0010_alter_ensayo_promedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensayo',
            name='promedia',
            field=models.FloatField(default='0.0'),
        ),
    ]
