# Generated by Django 3.2a1 on 2021-10-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensayo', '0012_alter_ensayo_promedia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ensayo',
            old_name='promedia',
            new_name='promedio',
        ),
    ]
