# Generated by Django 3.2a1 on 2021-10-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayo', '0014_remove_ensayo_promedio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensayo',
            name='promedio',
            field=models.CharField(default='0.0', max_length=100),
        ),
    ]
